[package]
name = "extract-bash-command"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.25.6"
tree-sitter-bash = "0.23.3"
rustop = "1.1.4"
streaming-iterator = "0.1.9"
