[package]
name = "extract-bash-command"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-bash = "0.20.5"
rustop = "1.1.4"
