name: Build executables
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup update stable

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cross    
      run: cargo install cross

    - name: Build an executable for x86_64-unknown-linux-musl
      run: |
        cross build --target x86_64-unknown-linux-musl --release 
    
    - name: upload release asset
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/x86_64-unknown-linux-musl/release/extract-bash-command
        asset_name: extract-bash-command-x86_64-unknown-linux-musl
        asset_content_type: application/octet-stream