name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup update stable

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install other Rust dependencies
      run: |
        rustup component add rustfmt clippy

    - name: Format check
      run: |
        cargo fmt --all -- --check
    
    - name: Run Clippy
      run: |
        cargo clippy -- -D warnings

    - name: Builds
      run: |
        cargo build
